### ISSUE TITLE
Error on Linux

### ISSUE THREAD

**Issue by Mx74** [stefanino-ch/lepg#1]
Hello,

On linux, archive downloaded, extracted, lepg.tcl launched, when chosing "Geometry processor" got:

couldn't read file "PreProcDirSelect.tcl": no such file or directory
couldn't read file "PreProcDirSelect.tcl": no such file or directory
    while executing
"source "PreProcDirSelect.tcl""
    (procedure "PreProcDirSelect_lepg" line 2)
    invoked from within
"PreProcDirSelect_lepg"
    invoked from within
".#menu.#menu#settings invoke active"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list $w invoke active]"
    (procedure "tk::MenuInvoke" line 50)
    invoked from within
"tk::MenuInvoke .#menu.#menu#settings 1"
    (command bound to event)

**Comment by stefanino-ch** [comment]
Yep, should be fixed now. There was an upper/lowercase issue related to filenames. Windows does not take care about this Linux does. Thanks for pointing out you're working on Linux this helped a lot. 
Just replace lepg.tcl by the one in the repository. All other files remain the samen. 
:-)

**Comment by Mx74** [comment]
Hello,

Issue is solved regarding this error message, but then both dialog boxes (for geometry and wing processors) are pre-filled, pointing on a win tree structure, looking for 2 .exe. 
I guess those .exe won't work on Linux.
Anyway, the dialog box are looking for some .out files only, and there is no .out file.

**Comment by stefanino-ch** [comment]
Hi 
By accident I've uploaded my config file I'm using for development, that's why you see initially a windows path pointing to an .exe file. Don't worry just change these settings to fit your setup. 

Now you should find an additional directory called lep-2_60-linux in the source tree. In there you have the lep directory containing the .out file for the wing processor and also the pre directory containing the .out file for the geometry processor. 
This should do the yob.
